### ISSUE TITLE
SDK_INVALID_REGION_ID 错误

### ISSUE THREAD

**Issue by qiu-xm** [gikoluo/aliyun-python-sdk-jaq#1]
在 pyramid 程序里引用了出错了
`
Can not find endpoint to access. Traceback (most recent call last):
  File "/test.py", line 280, in test
    result = clt.do_action_with_exception(request)
  File "/usr/local/lib/python2.7/dist-packages/aliyunsdkcore/client.py", line 241, in do_action_with_exception
    status, headers, body = self._implementation_of_do_action(acs_request)
  File "/usr/local/lib/python2.7/dist-packages/aliyunsdkcore/client.py", line 203, in _implementation_of_do_action
    endpoint = self._resolve_endpoint(request)
  File "/usr/local/lib/python2.7/dist-packages/aliyunsdkcore/client.py", line 167, in _resolve_endpoint
    error_msg.get_msg('SDK_INVALID_REGION_ID'))
ClientException: SDK.InvalidRegionId Can not find endpoint to access.
`
经过调试，发现好像是这个位置出错了
/usr/local/lib/python2.7/dist-packages/aliyunsdkjaq/request/v20161123/AfsCheckRequest.py
`
class AfsCheckRequest(RpcRequest):
	def __init__(self):
		RpcRequest.__init__(self, 'jaq', '2016-11-23', 'AfsCheck')
`
改成 RpcRequest.__init__(self, 'Jaq', '2016-11-23', 'AfsCheck') 好像正常了，是我打开方式不对吗？

**Comment by gikoluo** [comment]
这个值跟 aliyunsdkcore/endpoints.xml 下的配置有关。 
检查一下文件中这里的配置，是大写还是小写，或者两者都有。
<Product><ProductName>Jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>
<Product><ProductName>jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>

**Comment by gikoluo** [comment]
`<Product><ProductName>Jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>
 <Product><ProductName>jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>`

**Comment by gikoluo** [comment]
这个值跟 aliyunsdkcore/endpoints.xml 下的配置有关。
检查一下文件中这样的配置，是大写还是小写，或者两者都有。
`<Product><ProductName>Jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>`
`<Product><ProductName>jaq</ProductName><DomainName>jaq.aliyuncs.com</DomainName></Product>`
